# Generated by Django 2.2 on 2019-06-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes_db', '0002_auto_20190506_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('manufacturing_places', models.CharField(max_length=255)),
                ('countries', models.CharField(max_length=255)),
                ('store', models.CharField(blank=True, max_length=255)),
                ('nutriscore', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryDb',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='productdb',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitutes_db.CategoryDb'),
        ),
        migrations.AddField(
            model_name='historic',
            name='product_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_origin', to='substitutes_db.ProductDb'),
        ),
        migrations.AddField(
            model_name='historic',
            name='product_replaceable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_replaceable', to='substitutes_db.ProductDb'),
        ),
    ]
