# Generated by Django 2.2 on 2019-06-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes_db', '0003_auto_20190610_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='productdb',
            name='store',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Historic',
        ),
        migrations.AddField(
            model_name='historicdb',
            name='product_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_original', to='substitutes_db.ProductDb'),
        ),
        migrations.AddField(
            model_name='historicdb',
            name='product_replaceable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_replaceable', to='substitutes_db.ProductDb'),
        ),
    ]
